{
 "title": "Custom OTEL Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Job", "label": "Application", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  { "title": "Application Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(\"http_request_method\", \"http_route\") (rate({\"http_server_request_duration_seconds_count\", exported_job=\"$Job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(\"http_request_method\", \"http_route\") (rate({\"http_server_request_duration_seconds_sum\", exported_job=\"$Job\"}[$__rate_interval])/rate({\"http_server_request_duration_seconds_count\", exported_job=\"$Job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase({\"jvm_gc_duration_seconds_sum\", exported_job=\"$Job\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}